baseline_var <- c(
  "AGE",
  "FEMALE",
  "RACE",
  "ZIPINC_QRTL",
  "Insurance",
  "PL_NCHS",
  "HOSP_REGION",
  "HOSP_BEDSIZE",
  "HOSP_LOCTEACH",
  "charlindex",
  "htn",
  "CKD",
  "obesity",
  "dm",
  "CPD",
  "LiverDis",
  "PVD",
  "Hyperlipidemia",
  "CHF",
  "Cancer",
  "ObstructiveSleepApnea",
  "Arrhythmia",
  "ValvHD",
  "Smoking",
  "PriorStroke",
  "PreviousPCI",
  "PreviousCABG"
)

baseline_var_labels <- list(
  AGE ~ "Age, y",
  FEMALE ~ "Sex",
  RACE ~ "Race",
  ZIPINC_QRTL ~ "Residential income",
  Insurance ~ "Expected primary payer",
  PL_NCHS ~ "Level of urbanization",
  HOSP_REGION ~ "Hospital region",
  HOSP_BEDSIZE ~ "Hospital bedsize",
  HOSP_LOCTEACH ~ "Hospital location and teaching status",
  charlindex ~ "Charlson comorbidity index",
  htn ~ "Hypertension",
  obesity ~ "Obesity",
  dm ~ "Diabetes Mellitus",
  CPD ~ "Chronic pulmonary disease",
  CKD ~ "Chronic kidney disease",
  LiverDis ~ "Liver Disease",
  PVD ~ "Peripheral vascular disease",
  Hyperlipidemia ~ "Hyperlipidemia",
  ObstructiveSleepApnea ~ "Obstructive sleep apnea",
  CHF ~ "Congestive heart failure",
  Cancer ~ "Cancer",
  Arrhythmia ~ "Arrhythmia",
  ValvHD ~ "Valvular heart disease",
  Smoking ~ "Smoker",
  PriorStroke ~ "Prior stroke",
  PreviousPCI ~ "Prior PCI",
  PreviousCABG ~ "Prior CABG",
  Smoking ~ "Smoker"
)

outcome_var <- c(
  "DIED",
  "LOS",
  "adj_TOTCHG",
  "CardioShock",
  "CardiacArrest",
  "Stroke",
  "PCIProcedure",
  "CABGProcedure",
  "MACE"
)

outcome_var_labels <- list(
  DIED ~ "In-hospital mortality",
  LOS ~ "Length of stay (days)",
  adj_TOTCHG ~ "Adjusted total charges",
  CardioShock ~ "Cardiogenic shock",
  CardiacArrest ~ "Cardiac arrest",
  Stroke ~ "Stroke",
  PCIProcedure ~ "Percutaneous coronary intervention",
  CABGProcedure ~ "Coronary artery bypass grafting",
  MACE ~ "Major adverse cardiovascular event"
)

reg_var_labels <- list(
  AGE ~ "Age, y",
  FEMALE ~ "Sex",
  RACE ~ "Race",
  ZIPINC_QRTL ~ "Residential income",
  Insurance ~ "Expected primary payer",
  PL_NCHS ~ "Level of urbanization",
  HOSP_REGION ~ "Hospital region",
  HOSP_BEDSIZE ~ "Hospital bedsize",
  HOSP_LOCTEACH ~ "Hospital location and teaching status",
  charlindex ~ "Charlson comorbidity index",
  htn ~ "Hypertension",
  obesity ~ "Obesity",
  dm ~ "Diabetes Mellitus",
  CPD ~ "Chronic pulmonary disease",
  CKD ~ "Chronic kidney disease",
  LiverDis ~ "Liver Disease",
  PVD ~ "Peripheral vascular disease",
  Hyperlipidemia ~ "Hyperlipidemia",
  ObstructiveSleepApnea ~ "Obstructive sleep apnea",
  CHF ~ "Congestive heart failure",
  Cancer ~ "Cancer",
  Arrhythmia ~ "Arrhythmia",
  ValvHD ~ "Valvular heart disease",
  Smoking ~ "Smoker",
  PriorStroke ~ "Prior stroke",
  PreviousPCI ~ "Prior PCI",
  PreviousCABG ~ "Prior CABG",
  Smoking ~ "Smoker"
)
