baseline_var <- c(
  "AGE",
  "FEMALE",
  "RACE",
  "ZIPINC_QRTL",
  "Insurance",
  "PL_NCHS",
  "HOSP_REGION",
  "HOSP_BEDSIZE",
  "HOSP_LOCTEACH",
  "charlindex",
  "HTN",
  "CKD",
  "Obesity",
  "DM",
  "CPD",
  "PVD",
  "Hyperlipidemia",
  "CHF",
  "Cancer",
  "Arrhythmia",
  "Smoking",
  "PriorStroke"
)

baseline_var_labels <- list(
  AGE ~ "Age, y",
  FEMALE ~ "Sex",
  RACE ~ "Race",
  ZIPINC_QRTL ~ "Residential income",
  Insurance ~ "Expected primary payer",
  PL_NCHS ~ "Level of urbanization",
  HOSP_REGION ~ "Hospital region",
  HOSP_BEDSIZE ~ "Hospital bedsize",
  HOSP_LOCTEACH ~ "Hospital location and teaching status",
  charlindex ~ "Charlson comorbidity index",
  HTN ~ "Hypertension",
  Obesity ~ "Obesity",
  DM ~ "Diabetes Mellitus",
  CPD ~ "Chronic pulmonary disease",
  CKD ~ "Chronic kidney disease",
  PVD ~ "Peripheral vascular disease",
  Hyperlipidemia ~ "Hyperlipidemia",
  CHF ~ "Congestive heart failure",
  Cancer ~ "Cancer",
  Arrhythmia ~ "Arrhythmia",
  Smoking ~ "Smoker",
  PriorStroke ~ "Prior stroke"
)

outcome_var <- c(
  "DIED",
  "LOS",
  "adj_TOTCHG",
  "CardiacArrest",
  "Stroke",
  "WoundInfection",
  "Abcess",
  "Pneumonia",
  "DVT",
  "Hemorrhage",
  "PulmEmbolism",
  "RespFailure",
  "MechanicalVentilation"
)

outcome_var_labels <- list(
  DIED ~ "In-hospital mortality",
  LOS ~ "Length of stay (days)",
  adj_TOTCHG ~ "Adjusted total charges",
  CardiacArrest ~ "Cardiac arrest",
  Stroke ~ "Stroke",
  WoundInfection ~ "WoundInfection",
  Abcess ~ "Abcess",
  Pneumonia ~ "Pneumonia",
  DVT ~ "DVT",
  Hemorrhage ~ "Hemorrhage",
  PulmEmbolism ~ "PulmEmbolism",
  RespFailure ~ "RespFailure",
  MechanicalVentilation ~ "MechanicalVentilation"
)

reg_var_labels <- list(
  AGE ~ "Age, y",
  FEMALE ~ "Sex",
  RACE ~ "Race",
  ZIPINC_QRTL ~ "Residential income",
  Insurance ~ "Expected primary payer",
  PL_NCHS ~ "Level of urbanization",
  HOSP_REGION ~ "Hospital region",
  HOSP_BEDSIZE ~ "Hospital bedsize",
  HOSP_LOCTEACH ~ "Hospital location and teaching status",
  charlindex ~ "Charlson comorbidity index",
  HTN ~ "Hypertension",
  Obesity ~ "Obesity",
  DM ~ "Diabetes Mellitus",
  CPD ~ "Chronic pulmonary disease",
  CKD ~ "Chronic kidney disease",
  PVD ~ "Peripheral vascular disease",
  Hyperlipidemia ~ "Hyperlipidemia",
  CHF ~ "Congestive heart failure",
  Cancer ~ "Cancer",
  Arrhythmia ~ "Arrhythmia",
  Smoking ~ "Smoker",
  PriorStroke ~ "Prior stroke"
)
