project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "RCOP NIS-Cardio2"

format:
  html:
    theme: litera
    css: styles.css
    toc: true
  docx: default

execute:
  echo: false
  warning: false
  # enabled: false

